name: mapper

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - bwa
  - minimap2
  - bowtie2
  - samtools
  - deeptools
  - bedtools
  - bamtools
  - mosdepth
  - sambamba
  - subread
  - pip:
    - sequana>=0.18


